# Generated by Django 3.0.8 on 2020-07-24 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фотография заведения')),
                ('open_hour', models.IntegerField(verbose_name='Время открытия')),
                ('close_hour', models.IntegerField(verbose_name='Время закрытия')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес заведения')),
                ('average_cost_dish', models.IntegerField(blank=True, verbose_name='Средняя стоимость блюд')),
                ('coordinates_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=7, verbose_name='Координаты долгота')),
                ('coordinates_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=7, verbose_name='Координаты широта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец заведения')),
            ],
        ),
    ]
