# Generated by Django 3.0.8 on 2020-07-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200724_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='coordinates_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, verbose_name='Координаты широта'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='coordinates_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, verbose_name='Координаты долгота'),
        ),
    ]
