# Generated by Django 3.0.8 on 2020-07-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200724_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='average_cost_dish',
            field=models.IntegerField(blank=True, null=True, verbose_name='Средняя стоимость блюд'),
        ),
    ]
