# Generated by Django 3.0.8 on 2020-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200726_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calorie_content', models.IntegerField(default=0, verbose_name='Калорийность ингредиента')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='dish_photos', verbose_name='Фотография блюда')),
                ('total_calorie_content', models.IntegerField(default=0, verbose_name='Суммарная калорийность блюда')),
                ('price', models.IntegerField(verbose_name='Цена блюда')),
                ('ingredients', models.ManyToManyField(blank=True, to='core.Ingredient', verbose_name='Ингредиенты блюда')),
            ],
        ),
    ]
