# Generated by Django 3.0.8 on 2020-07-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dish_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cafe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.Cafe'),
        ),
    ]
