# Generated by Django 3.0.8 on 2020-07-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200728_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.Cafe'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='core.Ingredient', verbose_name='Ингредиенты блюда'),
        ),
    ]
