# Generated by Django 3.0.8 on 2020-07-30 09:04

from django.db import migrations
from apps.core.scripts import parse


def add_ingredients(apps, schema_editor):
    """
    Функция создает в бд ингредиенты из данных,
    которые мы спарсили, исходя из условия задания.
    """
    ingredient = apps.get_model('core', 'Ingredient')
    list_of_ingredients = parse()
    for obj in list_of_ingredients:
        ingredient.objects.create(
            name=obj[0],
            calorie_content=obj[1]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200729_0104'),
    ]

    operations = [
        migrations.RunPython(add_ingredients)
    ]
